articles/urls.py
from django.urls import path
from articles import views

#index 이름 이겹치는 경우가 있으니 해당 앱의 이름을 적어주면 장고에서도 혼란이 오지 않음!
app_name = 'articles'
urlpatterns = [
    path('index/', views.index),
    path('dinner/', views.dinner, name='dinner'), #변수를 지정가능함
    path('review/', views.review, name='review'),
    path('create_review/', views.create_review, name='create_review'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    
]

turtle_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    #앱이 많아 지기 때문에 해당 관련된 app에 url를 각자로 만들어 주고 큰 틀에는 포함시켜 준다는 include 사용해서 포함시킴
    path('articles/', include('articles.urls'))
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model): 
    # id 는 자동으로 만들어진다.
    title = models.CharField(max_length=10)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)

foods/models.py
from django.db import models

# Create your models here.

articles/views.py
import random
from turtle import title
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
def index(request):
    return render(request, 'index.html')

# 저녁메뉴 렌덤으로 선택
def dinner(request):
    menus = [{'name':'족발','price':3000}, 
            {'name':'햄버거','price':4000}, 
            {'name':'피자','price':2000}, 
            {'name':'치킨','price':8000}, 
            {'name':'초밥','price':9000}, 
            {'name':'닭발','price':6000}]
    pick = random.choice(menus)
    # order_by('-pk')이용해서 배열 거꾸로
    articles = Article.objects.order_by('-pk')
    context = {
        'pick': pick,
        'menus': menus,
        'articles' : articles,
    }
    return render(request, 'dinner.html', context)

def review(request):
    return render(request, 'review.html')

#request로 받은 메소드가 post 일때 create_review함수 작동
def create_review(request):
    content = request.POST.get('content')
    title = request.POST.get('title')
    article = Article(title=title, content=content)
    article.save()
   
    return redirect('articles:detail', article.pk)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article':article,
    }
    return render(request, 'detail.html', context)

def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        article.delete()
    return redirect('articles:dinner')

# 수정할 글 불러오기
def edit(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article':article,
    }
    return render(request, 'edit.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', article.pk)

foods/views.py
from django.shortcuts import render

# Create your views here.

articles/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>오늘 뭐먹지</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
   
</head>

<body class="container">
    <!-- 상속시키는 부분 content안에 들어간다 -->
    {% block content %} {% endblock %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
        </script>
</body>

</html>

articles/templates/detail.html
{% extends 'base.html' %}
{% block content %} 
<h2 class="text-center">DETAIL</h2>
<h3>{{ article.pk }}번째 글</h3>
<br />
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>
<p>작성 시각: {{  article.create_at|date:"SHORT_DATE_FORMAT" }}</p>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-danger">DELETE</button>
</form>
<a href="{%url 'articles:edit' article.pk %}" class="btn btn-primary">EDIT</a><br>
<!-- a태그는 url 형식의 get 방식으로 지워지는 방식 -->
<!-- <a href="{% url 'articles:delete' article.pk %}">[delete]</a> -->
<a href="{% url 'articles:dinner' %}">[back]</a>
<br />



{% endblock %}

articles/templates/dinner.html
{% extends 'base.html' %} {% block content %} 
<h1>오늘 님의 저녁은 {{pick.name}} 입니다.</h1>
<h1>메뉴 리스트</h1>
<ur>
    {% for menu in menus %}
    <li>{{menu.name}} {{menu.price}}</li>
    {% endfor %}
</ur>

{% if pick.price > 8000 %}
<p>비싸다!!</p>
{% elif pick.price > 4000 %}
<p>해볼만 하다!!</p>
{% else %}
<p>맛있겠다!</p>
<!-- #장고의 템플릿 문법으로 파이썬이랑 다르게 if,for 끝맺음을 해줘야함 -->
{% endif %} 

<h1>리뷰 리스트</h1>
<a href="{% url 'articles:review' %}">[리뷰 작성하기]</a>
{% for article in articles %} 
<p>글 번호 : {{ article.pk }}</p>
<p>글 제목 : {{ article.title }}</p>
<p>글 내용 : {{ article.content }}</p>
<a href="{% url 'articles:detail' article.pk %}">[detail]</a>
<!-- hr:글 구분선을 넣어줌 -->
<hr />
{% endfor %}
{% endblock %}

articles/templates/edit.html
{% extends 'base.html' %} 

{% block content %} 
<h1 class="text-center">EDIT</h1>
<form class="form-group" action="{%url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">Tititle: </label>
    <input class="form-control" type="text" name="title" value="{{ article.title }}"/><br />
    <label for="content">Content: </label>
    <textarea class="form-control" name="content" cols="30" rows="5">{{ article.content }}</textarea><br />
    <input type="submit">

</form>



{% endblock %}

articles/templates/index.html
<h1>거북이반 최윤선 화이티디디이이</h1>

articles/templates/review.html
{% extends 'base.html' %} {% block content %} 



<form 
    class="form-group"
    action="{% url 'articles:create_review' %}" 
    method="POST">
    {% csrf_token %}
    <label for="title">Tititle: </label>
    <input class="form-control" type="text" name="title" /><br />
    <label for="content">Content: </label>
    <input class="form-control" name="content" cols="30" rows="5"></textarea><br />
    <input type="Submit" />
</form>





{% endblock %}

articles/templates/review_result.html
<h1>보내서 받은 내용은 {{ content }}입니다.</h1>